### ISSUE TITLE
Not all goal data retrieved

### ISSUE THREAD

**Issue by jacobthurman** [chrisle/gattica#5]
Goal data is not retrieved for 'event' goals.

On one website, I have 1 goal (#1) that is a 'url destination' goal, and 4 other goals that are all events (#2, 6, 11, and 12). When calling account.goals in Gattaca, only one goal (#1) is returned.

I can still get the metrics for the other goals, they just aren't returned by account.goals.

**Comment by chrisle** [comment]
The Google Analytics API itself  doesn't return event goals when you ask it for goals. 
v3 i believe does it, but i'm not sure yet.
